### ISSUE TITLE
bug: Run fails with `Mount failed: invalid argument`

### ISSUE THREAD

**Issue by matoous** [shuveb/containers-the-hard-way#3]
Hi!

Today I tried to run `gocker` on my MacOS using following setup:

1. I used docker: `docker run --rm -it --cap-add=NET_ADMIN --cap-add=SYS_ADMIN --security-opt apparmor:unconfined ubuntu:latest`
2. I installed all necessary things (`git`, `iptables`, `build-essential`, `sudo`, `golang`)
3. I compiled the binary
4. I tried to run it using `sudo ./gocker run alpine /bin/sh`

The run command failed with:

```
2020/08/19 22:33:40 Cmd args: [./gocker run alpine /bin/sh]
2020/08/19 22:33:40 New container ID: 759be7783396
2020/08/19 22:33:40 Downloading metadata for alpine:latest, please wait...
2020/08/19 22:33:42 imageHash: a24bb4013296
2020/08/19 22:33:42 Checking if image exists under another name...
2020/08/19 22:33:42 Image doesn't exist. Downloading...
2020/08/19 22:33:51 Successfully downloaded alpine
2020/08/19 22:33:51 Uncompressing layer to: /var/lib/gocker/images/a24bb4013296/fe8bebfdf212/fs
2020/08/19 22:33:51 Image to overlay mount: a24bb4013296
2020/08/19 22:33:51 Mount failed: invalid argument
```

E.g. on following line: https://github.com/shuveb/containers-the-hard-way/blob/d90997c/run.go#L53 for call
```
syscall.Mount("none", contFSHome+"/mnt", "overlay", 0, mntOptions)
```

Do you please know why/what might be the reason?

**Comment by shuveb** [comment]
A container does not provide the right environment in which to run Gocker. If you want to run this on macOS, please run a Linux virtual machine and run Gocker inside of it.
